# <center> Numpy Basics </center>

In [1]:
#import numpy module with alias np
import numpy as np


We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [2]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it
ndarray = np.array([1,2,3])


In [3]:
# print output
ndarray


array([1, 2, 3])

## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [4]:
#define a,b,c and d as instructed above

a = np.array([10])
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])



Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [5]:
#print dimentions of a,b, c and d
print(np.ndim(a))
print(np.ndim(b))
print(np.ndim(c))
print(np.ndim(d))



1
1
2
3


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [6]:
# print shape of each a,b ,c and d

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

(1,)
(3,)
(2, 3)
(2, 2, 3)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [7]:
# print data type of c and d

print(c.dtype)
print(d.dtype)



int64
int64


Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function 

In [8]:
#print type of a and b variable
print(type(a))
print(type(b))




<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [9]:
# Lets check length of array b, using len() function
len(b)

3

Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy. 

In [10]:
# Lets check length of array c, using len() function
len(c)      

2

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [11]:
# Define l1,l2,l3 and l4 as stated above.
l1 = [10,20,30]
l2 = [40,50,60]
l3 = np.array(l1)
l4 = np.array(l2)



Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [12]:
#code here as instructed above

my_code = [a * b for a, b in zip(l1,l2)]
print(my_code)

[400, 1000, 1800]


Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [13]:
%timeit my_code
my_code_np = l3 * l4
print(my_code_np)
%timeit my_code_np              



11.7 ns ± 0.0779 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)
[ 400 1000 1800]
11.9 ns ± 0.146 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>


In [14]:
#Create a numpy array using arange with 1 and 11 as parameter in it

numpy_arange = np.arange(1,11)
numpy_arange

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [15]:
# Create an array using arange passing 1,11 and 2 as parameter in iter
numpy_arange1 = np.arange(1,11,2)
numpy_arange1



array([1, 3, 5, 7, 9])

In [16]:
# create numpy array using eye function with 3 as passed parameter

numpy_eye = np.eye(3)
numpy_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# Using arange() to generate numpy array x with numbers between 1 to 16
x = np.arange(0,16)
x



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
# Reshape x with 2 rows and 8 columns

x_reshape = x.reshape(2,8)
x_reshape

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [19]:
# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:


x_reshape2 = x.reshape(2,4,2)
x_reshape2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [20]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4
x_reshape3 = x.reshape(4,4)
x_reshape3


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
y=x.reshape(2,2,4)
y

# print y



array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [22]:
# Flattening y
y_flat = x.flatten()
y_flat


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
# Create an array a with all even numbers between 1 to 17
a = np.arange(2,17,2)
print(a) 


[ 2  4  6  8 10 12 14 16]


In [26]:
# Get third element in array a
a_third = a[2]
print(a_third)

6


In [27]:
#Print 3rd, 5th, and 7th element in array a
a_third = a[2]
print(a_third)
a_fifth = a[4]
print(a_fifth)
a_seventh = a[6]
print(a_seventh)



6
10
14


Lets check the same for 2 D array

In [28]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
# print the 3rd element from the 3rd row of a
print(a[2,2])


9


Well done!

Now lets check indexing for 3 D array 

In [30]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
b.ndim
b.shape
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [31]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.

print(b[1,0,2])


9


In [32]:
# Create 1D array

arr= np.array([1,2,3,4,5,6,7,8,9])




In [33]:
# Slice elements from 1st to 5th element from the following array:
arr_slice = arr[0:5]
print(arr_slice)



[1 2 3 4 5]


Note: The result includes the start index, but excludes the end index.



In [34]:
# Slice elements from index 5 to the end of the array:
arr_slice1 = arr[5:]
print(arr_slice1)


[6 7 8 9]


In [35]:
# Slice elements from the beginning to index 5 (not included):
arr_slice2 = arr[:5]
print(arr_slice2)





[1 2 3 4 5]


**STEP**

Use the step value to determine the step of the slicing:

In [36]:
# Print every other element from index 1 to index 7:
arr_slice3 = arr[7:]
print(arr_slice3)


[8 9]


Did you see? using step you were able to get alternate elements within specified index numbers.

In [37]:
# Return every other element from the entire array arr:
print(arr[::2])



[1 3 5 7 9]


well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**Array slicing in 2-D array.**

In [38]:
# Print array a
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
# From the third element, slice elements from index 1 to index 5 (not included) from array 'a'
print(a[2, 1:5])           



[8 9]


In [40]:
# In array 'a' print index 2 from all the elements :
print(a[:,2])



[3 6 9]


In [41]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:
print(a[:,1:])



[[2 3]
 [5 6]
 [8 9]]


Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [65]:

x1=   np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(x1)           



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [43]:
# assign x2 = x1
x2= x1              


In [44]:
#print x1 and x2
print(x1)
print(x2)   



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Ok now you have seen that both of them are same 

In [45]:
# change 1st element of x2 as 10
x2[0,0]=10
print(x2)
print(x1)       



[[10  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[10  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [46]:
#Again print x1 and x2
print(x1)
print(x2)

[[10  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[10  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [47]:
# Check memory share between x1 and x2
x1.base is x2.base      


True

Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [48]:
# Create a view of x1 and store it in x3.
x3 =  x1.view()


In [49]:
# Again check memory share between x1 and x3
x1.base is x3.base      



False

Woh! simple assignment is similar to view. That means 
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [50]:
#Change 1st element of x3=100
x3[0,0]=100
print(x3)
print(x1)   


[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]
[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [51]:
#print x1 and x3 to check if changes reflected in both
print(x1)
print(x3)   

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]
[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


Now its proved.

Lets see how **Copy()** function works

In [53]:
# Now create an array x4 which is copy of x1

x4=x1.copy()
# x4= --- IGNORE ---        
# Now create an array x4 which is copy of x1

x4=x1.copy()
x4[0,0]=1000
print(x4)
print(x1)       



[[1000    2    3    4    5]
 [   6    7    8    9   10]
 [  11   12   13   14   15]]
[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [54]:
# Change the last element of x4 as 900

x4[2,4]=900
print(x4)   



[[1000    2    3    4    5]
 [   6    7    8    9   10]
 [  11   12   13   14  900]]


In [55]:
# print both x1 and x4 to check if changes reflected in both
print(x1)
print(x4)       




[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]
[[1000    2    3    4    5]
 [   6    7    8    9   10]
 [  11   12   13   14  900]]


Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [56]:
#Check memory share between x1 and x4
x1.base is x4.base      



True

**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function: 

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [57]:
# stack x1 and x4 along columns.
x1_column_stack = np.column_stack((x1,x4))
x1_column_stack     


array([[ 100,    2,    3,    4,    5, 1000,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10,    6,    7,    8,    9,   10],
       [  11,   12,   13,   14,   15,   11,   12,   13,   14,  900]])

In [58]:
#stack x1 and x4 along rows
x1_row_stack = np.row_stack((x1,x4))
x1_row_stack    


C:\Users\USER\AppData\Local\Temp\ipykernel_7008\1440499477.py:2: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  x1_row_stack = np.row_stack((x1,x4))


array([[ 100,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10],
       [  11,   12,   13,   14,   15],
       [1000,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10],
       [  11,   12,   13,   14,  900]])

We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [60]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
##join arr1 and arr2 along rows using concatenate() function
arr_concatenate = np.concatenate((arr1,arr2),axis=0)
arr_concatenate 



array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
##join arr1 and arr2 along columns using concatenate() function
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
arr_concatenate_columns = np.concatenate((arr1,arr2),axis=1)
arr_concatenate_columns 


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [62]:
# append arr2 to arr1
arr1 = np.array([[1,2,3],[4,5,6]])          
arr2 = np.array([[7,8,9],[10,11,12]])
arr_append = np.append(arr1,arr2,axis=0)
arr_append


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Lets use insert() function which Inserts values into array before specified index value

In [96]:
# Inserts values into array x1 before index 4 with elements of x4     
x1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
x4 = x1.copy()  
x4[0,0] = 1000                                    
x1_insert = np.insert(x1,3,x4,axis=0)                   
x1_insert   

array([[   1,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10],
       [  11,   12,   13,   14,   15],
       [1000,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10],
       [  11,   12,   13,   14,   15]])

You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [77]:
# delete 2nd element from array x2
x2_delete = np.delete(x2,2)              
x2_delete   



array([100,   2,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15])

Did you see? 2 value is deleted from x2 which was at index position 2

Good Job learner! 

In [78]:
x2_delete

array([100,   2,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15])